app:
  env: local
  httpaddr: 127.0.0.1
  httpport: 3001

db:
  driver: mysql
  host: localhost
  port: 3306
  name: jasmine_feed_out
  user: root
  password:

dbhotel:
  driver: mysql
  host: localhost
  port: 3306
  name: jasmine_hotel
  user: root
  password:

sentry:
  sentrydsn: